name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: "nvmrc"
            use_nvmrc: true
          - label: "node18"
            node: "18.x"
          - label: "node20"
            node: "20.x"
          - label: "node22"
            node: "22.x"

    steps:
      - uses: actions/checkout@v3

      - name: Use Node from .nvmrc
        if: ${{ matrix.use_nvmrc }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Use Node ${{ matrix.node }}
        if: ${{ !matrix.use_nvmrc }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm test
